name: gql_dedupe_link
version: 2.0.0
description: GQL Link to deduplicate identical in-flight execution requests
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.3.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  async: ^2.5.0
dev_dependencies: 
  test: ^1.16.2
  mockito: ^5.0.0-nullsafety.7
  gql: ^0.13.0
  gql_pedantic: ^1.0.2
dependency_overrides: 
  gql_pedantic: 
    path: ../../gql_pedantic
  cats: 
    path: ../../cats
  gql: 
    path: ../../gql
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_websocket_link: 
    path: ../gql_websocket_link
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_error_link: 
    path: ../gql_error_link
  gql_code_builder: 
    path: ../../codegen/gql_code_builder
  gql_build: 
    path: ../../codegen/gql_build
  gql_example_http_auth_link: 
    path: ../../examples/gql_example_http_auth_link
  gql_dio_link: 
    path: ../gql_dio_link
  gql_example_dio_link: 
    path: ../../examples/gql_example_dio_link
  gql_example_cli_github: 
    path: ../../examples/gql_example_cli_github
  gql_example_cli: 
    path: ../../examples/gql_example_cli
  gql_example_build: 
    path: ../../examples/gql_example_build
  end_to_end_test: 
    path: ../../codegen/end_to_end_test
